apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: coreos-prom-redis
  namespace: cache
spec:
  version: "4.0-v1"
  terminationPolicy: WipeOut
  storage:
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: monitoring
      labels:
        release: prometheus-operator-1594318780
      interval: 10s
