apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: myapp
  namespace: my-namespace
spec:
  ports:
  - name: http-metrics 
    port: 5000
    protocol: TCP
    targetPort: http-metrics 
  selector:
    app: myapp
  type: ClusterIP
status:
  loadBalancer: {}
