apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus-operator-1594318780
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2020-07-09T18:19:51Z"
  labels:
    app: prometheus-operator-operator
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-operator-8.15.14
    heritage: Helm
    release: prometheus-operator-1594318780
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app: {}
          f:app.kubernetes.io/managed-by: {}
          f:chart: {}
          f:heritage: {}
          f:release: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":443,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":8080,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
          f:release: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Update
    time: "2020-07-09T18:19:51Z"
  name: prometheus-operator-159431-operator
  namespace: monitoring
  resourceVersion: "268976"
  selfLink: /api/v1/namespaces/monitoring/services/prometheus-operator-159431-operator
  uid: 8ee4e8d3-5d28-44b5-a10b-8f6d73ed1cf8
spec:
  clusterIP: 10.110.94.196
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: prometheus-operator-operator
    release: prometheus-operator-1594318780
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
